- id: '1647201637953'
  alias: Fråga MQTT om status vid omstart
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: sonoffs/cmnd/state
  mode: single
- id: '1647202126834'
  alias: Tänd renhorn vid solnedgång
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:30:00
  condition: []
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.renhorn
  mode: single
- id: '1647202175219'
  alias: Släck renhorn vid soluppgång
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 00:30:00
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.renhorn
  mode: single
- id: '1647375809481'
  alias: Scenario natt 22:00
  description: ''
  trigger:
  - platform: time
    at: '22:00:00'
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.natt
    metadata: {}
  mode: single
- id: '1647806400382'
  alias: Scenario kväll vid solnedgång
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -0:30:00
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.kvall
    metadata: {}
  mode: single
- id: '1651158313502'
  alias: Scenario dag kl 9:00
  description: ''
  trigger:
  - platform: time
    at: 09:00:00
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.dag
    metadata: {}
  mode: single
- id: '1681238896566'
  alias: Uppdaterat mögelindex krypgrund
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.mould_risk_krypgrund
    to:
  condition: []
  action:
  - service: notify.mobile_app_iphone_15
    data:
      title: Förändrat mögelindex Krypgrund
      message: '{{ states.sensor.template_mould_text_krypgrund.state }}'
  mode: single
- id: '1681239443452'
  alias: Uppdaterat mögelindex vind
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.mould_risk_vind
    to:
  condition: []
  action:
  - service: notify.mobile_app_iphone_15
    data:
      title: Förändrat mögelindex Vind
      message: '{{ states.sensor.template_mould_text_vind.state }}'
  mode: single
- id: '1681755399257'
  alias: Starta om sonoff om otillgänglig
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.sonoff1
    to: unavailable
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition: []
  action:
  - service: shell_command.reset_sonoff_1
    data: {}
  - service: shell_command.reset_sonoff_2
    data: {}
  - service: shell_command.reset_sonoff_3
    data: {}
  - service: shell_command.reset_sonoff_4
    data: {}
  mode: single
- id: '1688584850181'
  alias: Påminnelse bevattningspump 20 min
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.torkskap
    from:
    to: 'on'
    for:
      hours: 0
      minutes: 20
      seconds: 0
  condition: []
  action:
  - service: notify.mobile_app_iphone_15
    data:
      message: Pumpen har varit igång i 20 min.
      title: Bevattningspump
  - service: notify.mobile_app_linnea_iphone
    data:
      message: Pumpen har varit igång i 20 min.
      title: Bevattningspump
      data:
        actions:
        - action: TURN_OFF_PUMP
          title: Stäng av
          icon: sfsymbols:poweroff
  mode: single
- id: '1688585545081'
  alias: Stäng av pump genom actionable notification
  description: ''
  trigger:
  - platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: TURN_OFF_PUMP
  condition: []
  action:
  - service: notify.mobile_app_iphone_15
    data:
      message: Stänger av bevattningspump
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.torkskap
  mode: single
- id: '1688587074895'
  alias: Påminnelse bevattningspump 40 min
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.torkskap
    from:
    to: 'on'
    for:
      hours: 0
      minutes: 40
      seconds: 0
  condition: []
  action:
  - service: notify.mobile_app_iphone_15
    data:
      message: Pumpen har varit igång i 40 min.
      title: Bevattningspump
      data:
        actions:
        - action: TURN_OFF_PUMP
          title: Stäng av
          icon: sfsymbols:poweroff
  - service: notify.mobile_app_linnea_iphone
    data:
      message: Pumpen har varit igång i 40 min.
      title: Bevattningspump
      data:
        actions:
        - action: TURN_OFF_PUMP
          title: Stäng av
          icon: sfsymbols:poweroff
  mode: single
- id: '1690034035098'
  alias: 'Gräs: Slå på morgon'
  description: ''
  trigger:
  - platform: time
    at: 07:00:00
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.torkskap
  mode: single
- id: '1690034208771'
  alias: 'Gräs: Slå av morgon'
  description: ''
  trigger:
  - platform: time
    at: 07:10:00
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.torkskap
  mode: single
- id: '1690034252507'
  alias: 'Gräs: Slå av lunch'
  description: ''
  trigger:
  - platform: time
    at: '13:10:00'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.torkskap
  mode: single
- id: '1690034292028'
  alias: 'Gräs: Slå av kväll'
  description: ''
  trigger:
  - platform: time
    at: '22:10:00'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.torkskap
  mode: single
- id: '1690034364958'
  alias: 'Gräs: Slå på lunch'
  description: ''
  trigger:
  - platform: time
    at: '13:00:00'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.torkskap
  mode: single
- id: '1690034392304'
  alias: 'Gräs: Slå på kväll'
  description: ''
  trigger:
  - platform: time
    at: '22:00:00'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.torkskap
  mode: single
- id: '1692713872656'
  alias: Meddela Låg spänning UPS
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.ups_input_voltage
    for:
      hours: 0
      minutes: 0
      seconds: 5
    below: 100
  condition: []
  action:
  - service: notify.mobile_app_iphone_15
    data:
      message: Ingen inspänning till UPS
      title: Strömavbrott
  - service: notify.persistent_notification
    data:
      message: Ingen inspänning till UPS
      title: Strömavbrott
  mode: single
- id: '1697649932092'
  alias: Larma vid vatten under diskbänk
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.under_banken_fukt
    from:
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition: []
  action:
  - service: notify.mobile_app_iphone_15
    data:
      title: Vattenlarm
      message: Vatten under diskbänken
  - service: notify.persistent_notification
    data:
      message: Vatten under diskbänken
      title: Vattenlarm
  mode: single
- id: '1698351799743'
  alias: Tänd hos hönsen morgon
  description: ''
  trigger:
  - platform: time
    at: 07:00:00
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id:
      - switch.meross1_lampa
      - switch.honsen_dual_outlet_outdoor_switch_uttag_1
  mode: single
- id: '1698736019247'
  alias: Starta Nextcloud VM när cifs startat
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.cifs
    to: 'on'
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition:
  - condition: state
    entity_id: binary_sensor.nextcloud_2
    state: 'off'
    for:
      hours: 0
      minutes: 0
      seconds: 30
  action:
  - service: truenas.vm_start
    data: {}
    target:
      entity_id: binary_sensor.nextcloud_2
  mode: single
- id: '1699199627146'
  alias: Släck hos hönsen 20:00
  description: ''
  trigger:
  - platform: time
    at: '20:00:00'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id:
      - switch.meross1_lampa
  mode: single
- id: '1700394061972'
  alias: Notifiera när utomhussensorn blir otillgänglig
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.netatmo_banedal_vardagsrum_utomhus_temperature
    from:
    to: unavailable
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition: []
  action:
  - service: notify.persistent_notification
    data:
      message: Tappade kontakten med Netatmo utomhussensor
      title: Otillgänglig sensor
  - service: notify.mobile_app_iphone_15
    data:
      message: Tappade kontakten med Netatmo utomhussensor
      title: Otillgänglig sensor
  mode: single
- id: '1700397332117'
  alias: Övervaka publik ip
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.myip
    - sensor.cloud_familjenekdahl_com
  condition:
  - condition: template
    value_template: '{{states(''sensor.cloud_familjenekdahl_com'') != states(''sensor.myip'')}}'
  action:
  - service: notify.mobile_app_iphone_15
    data:
      message: Publik IP och cloud.familjenekdahl.com stämmer inte överens.
      title: DNS problem
  mode: single
- id: '1700507672337'
  alias: Tänd hos barnen vid solnedgång
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -0:30:00
  condition: []
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id:
      - light.vidar_lampa
      - light.sveas_fonster
      - light.bollar
  mode: single
- id: '1700507793323'
  alias: Släck hos barnen 19:00
  description: ''
  trigger:
  - platform: time
    at: '19:00:00'
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.sveas_fonster
      - light.vidar_lampa
  mode: single
- id: '1700923047282'
  alias: Styr scenatio med IKEA Remote
  description: ''
  use_blueprint:
    path: niro1987/zha_ikea_tradfri_5button_remote_custom.yaml
    input:
      remote: e9099621dfcc534d97e28a2330b0a4cf
      dimdown_short:
      - service: scene.turn_on
        target:
          entity_id: scene.natt
        metadata: {}
      dimup_short:
      - service: scene.turn_on
        target:
          entity_id: scene.morgon
        metadata: {}
      power_short:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.vardagsrumsfonster
- id: '1702492022726'
  alias: Släck hönsgård 18:30
  description: ''
  trigger:
  - platform: time
    at: '18:30:00'
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id: light.honsgard
    data: {}
  mode: single
- id: '64564645'
  alias: persistent_notification_log
  trigger:
  - platform: event
    event_type: call_service
    event_data:
      domain: persistent_notification
      service: create
  action:
  - service: notify.pn_log
    data_template:
      message: '{{ now().strftime(''%Y%m%d %H%M%S'') }}  {{ trigger.event.data.service_data.title
        }} /  {{ trigger.event.data.service_data.message }}

        '
  mode: single
