button_card_templates:
  !include_dir_merge_named button_card_templates

views:
  - type: custom:grid-layout
    path: 0
    layout:
      #default
      margin: 0
      grid-gap: var(--custom-layout-card-padding)
      grid-template-columns: repeat(4, 1fr) 0
      grid-template-rows: 0 repeat(2, fit-content(100%)) 0fr
      grid-template-areas: |
        "sidebar  .           .       .       ."
        "sidebar  lampor      ute     sovrum  ."
        "sidebar  heater      övrigt  hemma   ."
        "sidebar  footer      footer  footer  ."
      mediaquery:
        #phone
        "(max-width: 800px)":
          grid-gap: calc(var(--custom-layout-card-padding) * 1.7)
          grid-template-columns: 0 repeat(2, 1fr) 0
          grid-template-rows: 0 repeat(5, fit-content(100%)) 0fr
          grid-template-areas: |
            ".  .           .        ."
            ".  sidebar     sidebar  ."
            ".  lampor      sovrum   ."
            ".  ute         övrigt   ."
            ".  heater      hemma    ."
            ".  footer      footer   ."
            ".  .           .        ."
        #portrait
        "(max-width: 1200px)":
          grid-gap: var(--custom-layout-card-padding)
          grid-template-columns: repeat(3, 1fr) 0
          grid-template-rows: 0 repeat(3, fit-content(100%)) 0fr
          grid-template-areas: |
            "sidebar  .           .       ."
            "sidebar  lampor      sovrum  ."
            "sidebar  ute         övrigt  ."
            "sidebar  heater      hemma   ."
            "sidebar  footer      footer  ."
            "sidebar  .           .       ."
    cards:

      - type: custom:button-card #extra_styles fix
        styles: {card: [display: none]}

      #################################################
      #                                               #
      #                    SIDEBAR                    #
      #                                               #
      #################################################

      - type: vertical-stack
        view_layout:
          grid-area: sidebar
        cards:

          - type: custom:button-card
            entity: sensor.template_sidebar
            template: sidebar

          - type: conditional
            conditions:
              - entity: input_boolean.laundry_display
                state: 'on'
            card:
              type: custom:button-card
              entity: timer.laundry
              hold_action:
                action: call-service
                service: input_boolean.turn_off
                service_data:
                  entity_id: input_boolean.laundry_display
              template: laundry

      #################################################
      #                                               #
      #                  LAMPOR                       #
      #                                               #
      #################################################

      - type: grid
        title: Lampor
        view_layout:
          grid-area: lampor
        columns: 2
        cards:

          - type: custom:button-card
            entity: light.vardagsrumsfonster
            name: Fönster
            template:
              - light
              - icon_hue

          - type: custom:button-card
            entity: light.renhorn
            name: Renhorn
            template:
              - light
              - icon_shade

          - type: custom:button-card
            entity: light.fonsterlampa_kok
            name: Kök
            template:
              - light
              - icon_lamp

          - type: custom:button-card
            entity: light.fonsterlampa
            name: Tvättstuga
            template:
              - light
              - icon_lamp

      #################################################
      #                                               #
      #                    UTE                     #
      #                                               #
      #################################################

      - type: grid
        title: Ute
        view_layout:
          grid-area: ute
        columns: 2
        cards:

          - type: custom:button-card
            entity: light.huvudentre
            name: Huvudentré
            template:
              - light
              - icon_closet

          - type: custom:button-card
            entity: light.groventre
            name: Groventré
            template:
              - light
              - icon_closet

          - type: custom:button-card
            entity: light.garageport_2
            name: Garageport
            template:
              - light
              - icon_hue

      #################################################
      #                                               #
      #                    SOVRUM                     #
      #                                               #
      #################################################

      - type: grid
        title: Sovrum
        view_layout:
          grid-area: sovrum
        columns: 2
        cards:

          - type: custom:button-card
            entity: light.sveas_fonster
            name: Sveas fönster
            template:
              - light
              - icon_shade

          - type: custom:button-card
            entity: light.bollar
            name: Sveas bollar
            template:
              - light
              - icon_shade

          - type: custom:button-card
            entity: light.vidars_fonster
            name: Vidars fönster
            template:
              - light
              - icon_shade

      #################################################
      #                                               #
      #                     HEATER                     #
      #                                               #
      #################################################

      - type: grid
        title: Motorvärmare
        view_layout:
          grid-area: heater
        columns: 2
        cards:

          - type: custom:button-card
            name: Auris
            icon: mdi:car-hatchback
            color: rgb(28, 128, 199)
            tap_action:
              !include popup/auris.yaml
            template:
              - icon_name

          - type: custom:button-card
            name: Yaris
            icon: mdi:car-side
            color: rgb(145, 28, 36)
            tap_action:
              !include popup/yaris.yaml
            template:
              - icon_name

      #################################################
      #                                               #
      #                    ÖVRIGT                     #
      #                                               #
      #################################################

      - type: grid
        title: Övrigt
        view_layout:
          grid-area: övrigt
        columns: 2
        cards:

          - type: custom:button-card
            entity: switch.single_switch_socket_1
            name: Hönslampa
            template:
              - light
              - icon_chickenhouse

          - type: custom:button-card
            entity: switch.torkskap
            name: Bevattningspump
            template:
              - light
              - icon_watercan
          

          - type: custom:button-card
            entity: light.floalt_panel
            name: LED Panel Garage
            template:
              - light
              - icon_lamp

          - type: custom:button-card
            entity: light.garderob_wiz
            name: Garderob
            color: rgb(28, 128, 199)
            template:
              - light
              - icon_window

      #################################################
      #                                               #
      #                     HEMMA                     #
      #                                               #
      #################################################

      - type: grid
        title: Hemma
        view_layout:
          grid-area: hemma
        columns: 2
        cards:
          - type: custom:button-card
            entity: climate.banedal_3
            name: Klimat
            hold_action:
              !include popup/sovrum_klimat.yaml
            template:
              - base
              - icon_climate
              - climate
            variables:
              circle_input: >
                [[[
                  if (entity) {
                    return entity.state === 'cool' ?
                      entity.attributes.temperature :
                      entity.attributes.current_temperature;
                  }
                ]]]

      #################################################
      #                                               #
      #                    FOOTER                     #
      #                                               #
      #################################################

      - type: horizontal-stack
        view_layout:
          grid-area: footer
        cards:
          - type: custom:button-card
            name: >
              <ha-icon icon="mdi:home-thermometer"></ha-icon> Miljö
            tap_action:
              !include popup/footer/miljo.yaml
            template: footer

          - type: custom:button-card
            name: >
              <ha-icon icon="mdi:home-lightning-bolt"></ha-icon> Energi
            tap_action:
              !include popup/footer/energy.yaml
            template: footer

          - type: custom:button-card
            name: >
              <ha-icon icon="mdi:seed"></ha-icon> Pollen
            tap_action:
              !include popup/footer/pollen.yaml
            template: footer

          - type: custom:button-card
            name: >
              <ha-icon icon="mdi:radiator"></ha-icon> Uppdatera
            tap_action:
              !include popup/footer/updater.yaml
            variables:
              notify: >
                [[[
                  let hass_installed = states['sensor.current_version'].state,
                    hacs = states['sensor.hacs'],
                    hass_version_latest = states['sensor.docker_hub'].state,
                    hass_count = hass_installed !== hass_version_latest ? 1 : 0;
                  return hass_count + parseInt(hacs.state);
                ]]]
            template: footer
